version: '3.9'

services:
  front:
    build: ./front
    env_file:
      - .env
    ports:
      - 3000:3000
    volumes:
      - ./front:/usr/src/app
    command: npm run dev
  back:
    build: .
    env_file:
      - .env
    ports:
      - 3010:3010
    depends_on:
      - db
    volumes:
      - back:/usr/src/app
    command: air cmd.main.go -b 0.0.0.0
  db:
    image: postgres:alpine
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
  back:
  front: