FROM golang:latest

WORKDIR /usr/src/app/api

# cd into the api direcory and run go mod init github.com/Instagram-Go-API/api

RUN go mod init github.com/Instagram-Go-API/api

RUN go get github.com/gofiber/fiber/v2

RUN go get github.com/cosmtrek/air

RUN go install github.com/cosmtrek/air@latest

COPY . .

RUN go mod tidy

EXPOSE 3010